### PR TITLE
feature/dockerfile

### PR DESCRIPTION
**Pull request by dallemon**
create dockerfile using chainguard images
[chainguard info](https://www.chainguard.dev/chainguard-images)

### CODE REVIEW

**Review by tykling — APPROVED** [review]

**Comment by tykling** [comment]
great :+1: thanks!

**Comment by tykling** [comment]
two things, there should be a default config file (it can be an empty yaml file) loaded with `-c` or `--config-file` so it is possible to load a config file. And the port (default is `15353`) should be exposed.

**Comment by dallemon** [comment]
added empty config file during image build
exposed the default port
add experimental dockerhub publish actions, but needs some testing :)

**Comment by tolleiv** [comment]
Atm. the service is bound to 127.0.0.1 within https://github.com/tykling/dns_exporter/blob/develop/src/dns_exporter/entrypoint.py#L157 - while you might be able to build the container successfully, I think the bind address should be changed so the container can actually be used.

**Comment by zied-jt** [comment]
@dallemon thank you for this contribution !

@tykling is there any news about this PR ? As I plan to add `dns_exporter` to https://github.com/prometheus-community/helm-charts and we need at least a docker image. Also, as @tolleiv find out, we need having `0.0.0.0` in stead of `127.0.0.1` on https://github.com/tykling/dns_exporter/blob/develop/src/dns_exporter/entrypoint.py#L157:
```python
    HTTPServer(("0.0.0.0", args.port), handler).serve_forever()
```

**Comment by tykling** [comment]
ok so e25b3569fb272b202347d0ea458494b2e619c752 adds a command-line option to set the listening IP, which should make the Dockerfile a bit cleaner

**Review by tykling — APPROVED** [review]

**Comment by zied-jt** [comment]
Thank you @tykling

**Pull request merged**
